//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pvfUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pvfUtility.Properties.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 二进制Ani文件解析失败，查看“输出”窗口了解更多信息。 的本地化字符串。
        /// </summary>
        internal static string AniParseError {
            get {
                return ResourceManager.GetString("AniParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ani文件`{2}`在读取[FRAME{0}]的DAMAGE BOX &amp; ATTACK BOX 数据时时，第{1}字节错误。 的本地化字符串。
        /// </summary>
        internal static string AniReadBoxDataError {
            get {
                return ResourceManager.GetString("AniReadBoxDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANI文件`{0}`在读取时，发生错误:{1} 的本地化字符串。
        /// </summary>
        internal static string AniReadError {
            get {
                return ResourceManager.GetString("AniReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANI文件`{2}`在读取[FRAME{0}]的子项数据时时，第{1}字节错误。 的本地化字符串。
        /// </summary>
        internal static string AniReadFrameDataError {
            get {
                return ResourceManager.GetString("AniReadFrameDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ANI文件`{2}`在读取[FRAME{0}]的IMAGE数据时时，第{1}字节错误。 的本地化字符串。
        /// </summary>
        internal static string AniReadImageError {
            get {
                return ResourceManager.GetString("AniReadImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ani文件`{1}`在读取全局数据时，第{0}字节错误。 的本地化字符串。
        /// </summary>
        internal static string AniReadOverAllItemError {
            get {
                return ResourceManager.GetString("AniReadOverAllItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件`{0}`时，发生错误:{1} 的本地化字符串。
        /// </summary>
        internal static string AniSaveError {
            get {
                return ResourceManager.GetString("AniSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件`{1}`时，在全局数据中，未能识别数据或格式出错：`{0}`。 的本地化字符串。
        /// </summary>
        internal static string AniSaveOverAllItemError {
            get {
                return ResourceManager.GetString("AniSaveOverAllItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件`{2}`时，在[FRAME{0}]中，未能识别数据`{1}`。 的本地化字符串。
        /// </summary>
        internal static string AniSaveParseError {
            get {
                return ResourceManager.GetString("AniSaveParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已处理“{0}”中所有文件。 的本地化字符串。
        /// </summary>
        internal static string BatchFinished {
            get {
                return ResourceManager.GetString("BatchFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理文件... 的本地化字符串。
        /// </summary>
        internal static string Batching {
            get {
                return ResourceManager.GetString("Batching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理中... 的本地化字符串。
        /// </summary>
        internal static string Busying {
            get {
                return ResourceManager.GetString("Busying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更换主题成功，你需要重启才能完全应用更改。 的本地化字符串。
        /// </summary>
        internal static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编译脚本文件时发生{0}个错误，查看【错误列表】了解详情。 的本地化字符串。
        /// </summary>
        internal static string CompileError {
            get {
                return ResourceManager.GetString("CompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到代码{0} 的本地化字符串。
        /// </summary>
        internal static string CouldnotFindStr {
            get {
                return ResourceManager.GetString("CouldnotFindStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除以下文件/文件夹？此操作将不可恢复，继续吗？ 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑器 的本地化字符串。
        /// </summary>
        internal static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本内容为空 的本地化字符串。
        /// </summary>
        internal static string EditorNullText {
            get {
                return ResourceManager.GetString("EditorNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误： 的本地化字符串。
        /// </summary>
        internal static string ExceptionOccurred {
            get {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生异常!是否保存当前内存中的缓存？ 的本地化字符串。
        /// </summary>
        internal static string ExceptionOccurred2 {
            get {
                return ResourceManager.GetString("ExceptionOccurred2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功导出“{0}”，共导出了{1}条数据。 的本地化字符串。
        /// </summary>
        internal static string ExportTxtFinished {
            get {
                return ResourceManager.GetString("ExportTxtFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取文件终止 的本地化字符串。
        /// </summary>
        internal static string ExtractFileAbort {
            get {
                return ResourceManager.GetString("ExtractFileAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取完成. 的本地化字符串。
        /// </summary>
        internal static string ExtractFileComplete {
            get {
                return ResourceManager.GetString("ExtractFileComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取文件{0}到7z失败 的本地化字符串。
        /// </summary>
        internal static string ExtractFileTo7zError {
            get {
                return ResourceManager.GetString("ExtractFileTo7zError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取到7z压缩包 的本地化字符串。
        /// </summary>
        internal static string ExtractFileTo7zTitle {
            get {
                return ResourceManager.GetString("ExtractFileTo7zTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在解压压缩文件... 的本地化字符串。
        /// </summary>
        internal static string Extracting7z {
            get {
                return ResourceManager.GetString("Extracting7z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取{0}个项目... 的本地化字符串。
        /// </summary>
        internal static string ExtractingFile {
            get {
                return ResourceManager.GetString("ExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入终止。 的本地化字符串。
        /// </summary>
        internal static string ImportFileCancel {
            get {
                return ResourceManager.GetString("ImportFileCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功导入了{0}条数据至{1}。 的本地化字符串。
        /// </summary>
        internal static string ImportTxtFinished {
            get {
                return ResourceManager.GetString("ImportTxtFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pvfUtility 正忙 的本地化字符串。
        /// </summary>
        internal static string IsBusy {
            get {
                return ResourceManager.GetString("IsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取注释文件（Comment.xml）失败：： 的本地化字符串。
        /// </summary>
        internal static string LoadCommentException {
            get {
                return ResourceManager.GetString("LoadCommentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取解析器配置信息失败：： 的本地化字符串。
        /// </summary>
        internal static string LoadPraserInfoException {
            get {
                return ResourceManager.GetString("LoadPraserInfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入 {0}，发生错误：{1}，此文件损坏或存在重复项。 的本地化字符串。
        /// </summary>
        internal static string LoadStrError {
            get {
                return ResourceManager.GetString("LoadStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功从{0}载入Str文件。 的本地化字符串。
        /// </summary>
        internal static string LoadStrSuccess {
            get {
                return ResourceManager.GetString("LoadStrSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请等待上一个操作完成。 的本地化字符串。
        /// </summary>
        internal static string NeedWait {
            get {
                return ResourceManager.GetString("NeedWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pvfUtility 需要.NET 4.6.2 才能正确地运行,按&quot;确定&quot;打开下载页面. 的本地化字符串。
        /// </summary>
        internal static string NET462Required {
            get {
                return ResourceManager.GetString("NET462Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析文件{0}：：二进制比对报告异常。 的本地化字符串。
        /// </summary>
        internal static string PraserVerifyDataFailed {
            get {
                return ResourceManager.GetString("PraserVerifyDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析文件{0}：：数量统计报告异常。 的本地化字符串。
        /// </summary>
        internal static string PraserVerifyStructureFailed {
            get {
                return ResourceManager.GetString("PraserVerifyStructureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本文件格式异常，未能读取。 的本地化字符串。
        /// </summary>
        internal static string ReadScriptException {
            get {
                return ResourceManager.GetString("ReadScriptException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重载 {0}时，发现重复项{1}，这将导致文件损坏。 的本地化字符串。
        /// </summary>
        internal static string ReLoadStrError {
            get {
                return ResourceManager.GetString("ReLoadStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功重载： 的本地化字符串。
        /// </summary>
        internal static string ReLoadStrSuccess {
            get {
                return ResourceManager.GetString("ReLoadStrSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件{0}成功。 的本地化字符串。
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索完成，本次搜索结果总数：{0}。 的本地化字符串。
        /// </summary>
        internal static string SearchFinished {
            get {
                return ResourceManager.GetString("SearchFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索中... 的本地化字符串。
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用标识&apos;{0}&apos;错误 的本地化字符串。
        /// </summary>
        internal static string StrIndexError {
            get {
                return ResourceManager.GetString("StrIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的字符串引用 的本地化字符串。
        /// </summary>
        internal static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 stringtable.bin 载入成功，当前全局编码器： 的本地化字符串。
        /// </summary>
        internal static string StringTableLoadSuccess {
            get {
                return ResourceManager.GetString("StringTableLoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新已有文件：{0}发生错误。 的本地化字符串。
        /// </summary>
        internal static string UpdateFileError {
            get {
                return ResourceManager.GetString("UpdateFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功导入了{0}个文件。 的本地化字符串。
        /// </summary>
        internal static string UpdateFileFinish {
            get {
                return ResourceManager.GetString("UpdateFileFinish", resourceCulture);
            }
        }
    }
}
